---
includes:
  - docs/reqstream/build-mark/build-mark.yaml
  - docs/reqstream/build-mark/platform-requirements.yaml
  - docs/reqstream/build-mark/program.yaml
  - docs/reqstream/build-mark/cli/cli.yaml
  - docs/reqstream/build-mark/cli/context.yaml
  - docs/reqstream/build-mark/build-notes/build-notes.yaml
  - docs/reqstream/build-mark/build-notes/build-information.yaml
  - docs/reqstream/build-mark/build-notes/item-info.yaml
  - docs/reqstream/build-mark/build-notes/web-link.yaml
  - docs/reqstream/build-mark/self-test/self-test.yaml
  - docs/reqstream/build-mark/self-test/validation.yaml
  - docs/reqstream/build-mark/utilities/utilities.yaml
  - docs/reqstream/build-mark/utilities/path-helpers.yaml
  - docs/reqstream/build-mark/utilities/process-runner.yaml
  - docs/reqstream/build-mark/version/version.yaml
  - docs/reqstream/build-mark/repo-connectors/repo-connectors.yaml
  - docs/reqstream/build-mark/repo-connectors/repo-connector-base.yaml
  - docs/reqstream/build-mark/repo-connectors/item-router.yaml
  - docs/reqstream/build-mark/repo-connectors/item-controls-parser.yaml
  - docs/reqstream/build-mark/repo-connectors/repo-connector-factory.yaml
  - docs/reqstream/build-mark/repo-connectors/github/github-repo-connector.yaml
  - docs/reqstream/build-mark/repo-connectors/azure-devops/azure-devops-repo-connector.yaml
  - docs/reqstream/build-mark/repo-connectors/mock/mock-repo-connector.yaml
  - docs/reqstream/build-mark/configuration/configuration.yaml
  - docs/reqstream/ots/mstest.yaml
  - docs/reqstream/ots/reqstream.yaml
  - docs/reqstream/ots/buildmark.yaml
  - docs/reqstream/ots/versionmark.yaml
  - docs/reqstream/ots/sarifmark.yaml
  - docs/reqstream/ots/sonarmark.yaml
