package BuildMark {
    part def VersionSemantic {
        doc /* Semantic version with build metadata. */

        comment sourceRef /* Source: src/DemaConsulting.BuildMark/Version/VersionSemantic.cs */
        comment testRef /* Test: test/DemaConsulting.BuildMark.Tests/Version/VersionSemanticTests.cs */
        comment designRef /* Design: docs/design/build-mark/version/version-semantic.md */
        comment verificationRef /* Verification: docs/verification/build-mark/version/version-semantic.md */
        comment reqRef /* Requirements: docs/reqstream/build-mark/version/version-semantic.yaml */
    }
}
