package BuildMark {
    part def VersionIntervalSet {
        doc /* Ordered set of version intervals. */

        comment sourceRef /* Source: src/DemaConsulting.BuildMark/Version/VersionIntervalSet.cs */
        comment testRef /* Test: test/DemaConsulting.BuildMark.Tests/Version/VersionIntervalSetTests.cs */
        comment designRef /* Design: docs/design/build-mark/version/version-interval-set.md */
        comment verificationRef /* Verification: docs/verification/build-mark/version/version-interval-set.md */
        comment reqRef /* Requirements: docs/reqstream/build-mark/version/version-interval-set.yaml */
    }
}
