package BuildMark {
    part def ProcessRunner {
        doc /* Process runner for Git commands. */

        comment sourceRef /* Source: src/DemaConsulting.BuildMark/Utilities/ProcessRunner.cs */
        comment testRef /* Test: test/DemaConsulting.BuildMark.Tests/Utilities/ProcessRunnerTests.cs */
        comment designRef /* Design: docs/design/build-mark/utilities/process-runner.md */
        comment verificationRef /* Verification: docs/verification/build-mark/utilities/process-runner.md */
        comment reqRef /* Requirements: docs/reqstream/build-mark/utilities/process-runner.yaml */
    }
}
