package BuildMark {
    part def BuildInformation {
        doc /* Build information data model. */

        comment sourceRef /* Source: src/DemaConsulting.BuildMark/BuildNotes/BuildInformation.cs */
        comment testRef /* Test: test/DemaConsulting.BuildMark.Tests/BuildNotes/BuildInformationTests.cs */
        comment designRef /* Design: docs/design/build-mark/build-notes/build-information.md */
        comment verificationRef /* Verification: docs/verification/build-mark/build-notes/build-information.md */
        comment reqRef /* Requirements: docs/reqstream/build-mark/build-notes/build-information.yaml */
    }
}
