package BuildMark {
    part def MockRepoConnector {
        doc /* Mock repository connector for self-test. */

        comment sourceRef /* Source: src/DemaConsulting.BuildMark/RepoConnectors/Mock/MockRepoConnector.cs */
        comment testRef /* Test: test/DemaConsulting.BuildMark.Tests/RepoConnectors/Mock/MockRepoConnectorTests.cs */
        comment designRef /* Design: docs/design/build-mark/repo-connectors/mock/mock-repo-connector.md */
        comment verificationRef /* Verification: docs/verification/build-mark/repo-connectors/mock/mock-repo-connector.md */
        comment reqRef /* Requirements: docs/reqstream/build-mark/repo-connectors/mock/mock-repo-connector.yaml */
    }
}
