package BuildMark {
    part def Validation {
        doc /* Self-validation test runner. */

        comment sourceRef /* Source: src/DemaConsulting.BuildMark/SelfTest/Validation.cs */
        comment testRef /* Test: test/DemaConsulting.BuildMark.Tests/SelfTest/ValidationTests.cs */
        comment designRef /* Design: docs/design/build-mark/self-test/validation.md */
        comment verificationRef /* Verification: docs/verification/build-mark/self-test/validation.md */
        comment reqRef /* Requirements: docs/reqstream/build-mark/self-test/validation.yaml */
    }
}
