package BuildMark {
    part def AzureDevOpsRepoConnector {
        doc /* Azure DevOps API integration. */

        comment sourceRef /* Source: src/DemaConsulting.BuildMark/RepoConnectors/AzureDevOps/AzureDevOpsRepoConnector.cs */
        comment testRef /* Test: test/DemaConsulting.BuildMark.Tests/RepoConnectors/AzureDevOps/AzureDevOpsRepoConnectorTests.cs */
        comment designRef /* Design: docs/design/build-mark/repo-connectors/azure-devops/azure-devops-repo-connector.md */
        comment verificationRef /* Verification: docs/verification/build-mark/repo-connectors/azure-devops/azure-devops-repo-connector.md */
        comment reqRef /* Requirements: docs/reqstream/build-mark/repo-connectors/azure-devops/azure-devops-repo-connector.yaml */
    }
}
