package BuildMark {
    part def AzureDevOpsRestClient {
        doc /* REST API client. */

        comment sourceRef /* Source: src/DemaConsulting.BuildMark/RepoConnectors/AzureDevOps/AzureDevOpsRestClient.cs */
        comment testRef /* Test: test/DemaConsulting.BuildMark.Tests/RepoConnectors/AzureDevOps/AzureDevOpsRestClientTests.cs */
        comment designRef /* Design: docs/design/build-mark/repo-connectors/azure-devops/azure-devops-rest-client.md */
        comment verificationRef /* Verification: docs/verification/build-mark/repo-connectors/azure-devops/azure-devops-rest-client.md */
        comment reqRef /* Requirements: docs/reqstream/build-mark/repo-connectors/azure-devops/azure-devops-rest-client.yaml */
    }
}
