package BuildMark {
    part def WorkItemMapper {
        doc /* Work item to ItemInfo mapper. */

        comment sourceRef /* Source: src/DemaConsulting.BuildMark/RepoConnectors/AzureDevOps/WorkItemMapper.cs */
        comment testRef /* Test: test/DemaConsulting.BuildMark.Tests/RepoConnectors/AzureDevOps/WorkItemMapperTests.cs */
        comment designRef /* Design: docs/design/build-mark/repo-connectors/azure-devops/work-item-mapper.md */
        comment verificationRef /* Verification: docs/verification/build-mark/repo-connectors/azure-devops/work-item-mapper.md */
        comment reqRef /* Requirements: docs/reqstream/build-mark/repo-connectors/azure-devops/work-item-mapper.yaml */
    }
}
