package BuildMark {
    part def RepoConnectorBase {
        doc /* Repository connector base class. */

        comment sourceRef /* Source: src/DemaConsulting.BuildMark/RepoConnectors/RepoConnectorBase.cs */
        comment testRef /* Test: test/DemaConsulting.BuildMark.Tests/RepoConnectors/RepoConnectorBaseTests.cs */
        comment designRef /* Design: docs/design/build-mark/repo-connectors/repo-connector-base.md */
        comment verificationRef /* Verification: docs/verification/build-mark/repo-connectors/repo-connector-base.md */
        comment reqRef /* Requirements: docs/reqstream/build-mark/repo-connectors/repo-connector-base.yaml */
    }
}
