package BuildMark {
    part def RepoConnectorFactory {
        doc /* Repository connector factory. */

        comment sourceRef /* Source: src/DemaConsulting.BuildMark/RepoConnectors/RepoConnectorFactory.cs */
        comment testRef /* Test: test/DemaConsulting.BuildMark.Tests/RepoConnectors/RepoConnectorFactoryTests.cs */
        comment designRef /* Design: docs/design/build-mark/repo-connectors/repo-connector-factory.md */
        comment verificationRef /* Verification: docs/verification/build-mark/repo-connectors/repo-connector-factory.md */
        comment reqRef /* Requirements: docs/reqstream/build-mark/repo-connectors/repo-connector-factory.yaml */
    }
}
